### ISSUE TITLE
user database manager needs to queue requests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/wordlist#4]
I think we need to make sure that the user database manager queues all requests so that one can't trample on another. Take the following sequence:

* user requests to delete all items in her wordlist
* user does a new lookup

This will result in a deleteMany request to the database manager which is instructed to delete all items for a particular user and language, followed by an update request which is instructed to update/create an item for that user and language. If the latter gets processed before the former, the new word will be deleted with all the rest.  

We need to ensure that database requests are only processed in the order received

**Comment by irina060981** [comment]
I have added blocking workflow ro UserDataManager to to avoid described risk.
https://github.com/alpheios-project/wordlist/pull/7

**Comment by irina060981** [comment]
Merged and closed
