### ISSUE TITLE
RemoteDBAdapter implementation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/wordlist#5]
I have deployed a prototype User Word service for remote storage of user worditem data.
The api is as follows:

```
POST /words/{id} Creates a new item
Content (body): JSON serialization of the WordItem object

Response Codes:
201 Successful Creation
500 Failed Creation
401 Unauthorized

Successful Response Body: the newly created item
```

```
GET /words/{id} Gets an existing item

Response Codes:
200 Success
500 Failure
401 Unauthorized

Successful Response Body: the retrieved item 
Failed Response Body: {  status: false }

```

```
PUT /words/{id} Updates an existing item
Content (body): JSON serialization of the WordItem object

Response Codes:
200 Success
500 Failure
401 Unauthorized

Successful Response Body: {  status: true }

Failed Response Body: { status: false }
```

```
DELETE /words/{id} Deletes an item

Response Codes:
200 Success
500 Failure
401 Unauthorized

Successful Response Body: {  status: true }

Failed Response Body: { status: false}  

```

```
DELETE /words?languageCode={languageCode} Deletes all items for a particular language

Response Codes:
200 Success
500 Failure
401 Unauthorized

Successful Response Body: {  status: true }

Failed Response Body: { status: false }

```

```
GET /words?languageCode={languageCode} Lists all items for a particular language
POST /words?languageCode={languageCode} Lists all items for a particular language

Response Codes:
200 Success
500 Failure
401 Unauthorized

Successful Response Body: JSON list of all the retrieves items  
Failed Response Body: {  status: false }

```

All requests require a valid Auth0 bearer access token for the user to be sent in the `Authorization` header.

e.g.

```
Authorization: bearer {jwt}
```

For development and testing purposes a test user id (which will be rotated regularly) can be sent in place of the jwt in the Authorization header.

The word id is expected to be supplied by the client in the format:

```
{languageCode}-{targetWord}
```

Currently the server is agnostic as to the content of the word items.  I don't want us to store full Homonym data on the remote server, only the data needed for the list display. 

So perhaps we could start with a serialization that extras the lemmas from the homonym and puts them in a property in the serialized JSON, and then the adapter can recreate a bare homonym from that upon load from the database.

**Comment by irina060981** [comment]
https://github.com/alpheios-project/wordlist/pull/9
https://github.com/alpheios-project/data-models/pull/74
https://github.com/alpheios-project/components/pull/349

**Comment by irina060981** [comment]
Merged and closed
